In [4]:
import sqlite3
import pandas as pd

In [14]:
data = pd.DataFrame({'level': ['Junior', 'Mid-level', 'Senior'],
                      'salary': [7500, 14650, 18320],
                      'position': ['Data Analyst', 'Data Scientist', 'Data Engineer']})

In [13]:
file_path = 'database.db'
import pathlib
import os

if not os.path.exists(file_path):
    pathlib.Path(file_path).touch()
    print(f"File {file_path} created successfully!")
else:
    print(f"File {file_path} already exists!")
    # remove and recreate
    os.remove(file_path)
    pathlib.Path(file_path).touch()
    print(f"File {file_path} recreated successfully!")

File database.db already exists!
File database.db recreated successfully!

In [15]:
cnn = sqlite3.connect('database.db')

In [16]:
data.to_sql('employees',cnn)

3

In [17]:
%load_ext sql

In [18]:
%sql sqlite:///database.db

In [19]:
%%sql

SELECT * FROM employees

 * sqlite:///database.db
Done.

[(0, 'Junior', 7500, 'Data Analyst'),
 (1, 'Mid-level', 14650, 'Data Scientist'),
 (2, 'Senior', 18320, 'Data Engineer')]